apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookRental
  labels:
    app: bookRental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookRental
  template:
    metadata:
      labels:
        app: bookRental
    spec:
      containers:
        - name: bookRental
          image: username/bookRental:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5